const staticCategoryData = [
  {
    CATEGORY_NAME: "Appointment Order",
    DISPLAY_NAME: "Appointment Order",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Candidate Certificates",
    DISPLAY_NAME: "Candidate Certificates",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Candidate CV",
    DISPLAY_NAME: "Candidate CV",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Candidate Photo",
    DISPLAY_NAME: "Candidate Photo",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Client Agreement",
    DISPLAY_NAME: "Client Agreement",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Client Approvals (Others)",
    DISPLAY_NAME: "Client Approvals (Others)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Client Order",
    DISPLAY_NAME: "Client Order",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Completion Certificate",
    DISPLAY_NAME: "Completion Certificate",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Completion Certificates (Client)",
    DISPLAY_NAME: "Completion Certificates (Client)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Completion Certificates (Subcontract)",
    DISPLAY_NAME: "Completion Certificates (Subcontract)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Contract Termination Letter",
    DISPLAY_NAME: "Contract Termination Letter",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "CVI (Site Instructions)",
    DISPLAY_NAME: "CVI (Site Instructions)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "CVI - Site Instruction",
    DISPLAY_NAME: "CVI - Site Instruction",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Delivery Note",
    DISPLAY_NAME: "Delivery Note",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Drawings \u0026 Approvals",
    DISPLAY_NAME: "Drawings \u0026 Approvals",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Certificates",
    DISPLAY_NAME: "Employee Certificates",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Contract",
    DISPLAY_NAME: "Employee Contract",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Driving License",
    DISPLAY_NAME: "Employee Driving License",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee ID/Smart Card",
    DISPLAY_NAME: "Employee ID/Smart Card",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Leave Request",
    DISPLAY_NAME: "Employee Leave Request",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Letters(Guarantee)",
    DISPLAY_NAME: "Employee Letters(Guarantee)",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Passport",
    DISPLAY_NAME: "Employee Passport",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Photo",
    DISPLAY_NAME: "Employee Photo",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee RP/Visa",
    DISPLAY_NAME: "Employee RP/Visa",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Signature",
    DISPLAY_NAME: "Employee Signature",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Employee Warning Letters",
    DISPLAY_NAME: "Employee Warning Letters",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Estimation",
    DISPLAY_NAME: "Tender or Quotation",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Experience Letter (Company)",
    DISPLAY_NAME: "Experience Letter (Company)",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Final Account",
    DISPLAY_NAME: "Final Account",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Goverment Approvals (Project)",
    DISPLAY_NAME: "Goverment Approvals (Project)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Incoming Correspondence from Client",
    DISPLAY_NAME: "Incoming Correspondence from Client",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Incoming Correspondence from Suppliers",
    DISPLAY_NAME: "Incoming Correspondence from Suppliers",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Incoming Correspondences",
    DISPLAY_NAME: "Incoming Correspondences",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Invoice",
    DISPLAY_NAME: "Invoice",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Job Confirmation Letter",
    DISPLAY_NAME: "Job Confirmation Letter",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "MAS",
    DISPLAY_NAME: "MAS",
    MODULE_NAME: "PROJECT",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "MAS (Material Approvals)",
    DISPLAY_NAME: "MAS (Material Approvals)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Minutes of Meeting",
    DISPLAY_NAME: "Minutes of Meeting",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Minutes of the meeting",
    DISPLAY_NAME: "Minutes of the meeting",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Other Payment Request",
    DISPLAY_NAME: "Other Payment Request",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Outgoing Correspondence to Client",
    DISPLAY_NAME: "Outgoing Correspondence to Client",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Outgoing Correspondence to Suppliers",
    DISPLAY_NAME: "Outgoing Correspondence to Suppliers",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Outgoing Correspondences",
    DISPLAY_NAME: "Outgoing Correspondences",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Payment advices",
    DISPLAY_NAME: "Payment advices",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: 2048,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Payment Advices (Client)",
    DISPLAY_NAME: "Payment Advices (Client)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Payment Advices (Subcontract)",
    DISPLAY_NAME: "Payment Advices (Subcontract)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Project Agreement",
    DISPLAY_NAME: "Project Agreement",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Quotations from Suppliers",
    DISPLAY_NAME: "Quotations from Suppliers",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Relieving Letter (Company)",
    DISPLAY_NAME: "Relieving Letter (Company)",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "RFI (Request for Information)",
    DISPLAY_NAME: "RFI (Request for Information)",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Salary Revision Letters",
    DISPLAY_NAME: "Salary Revision Letters",
    MODULE_NAME: "HR",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Subcontract Agreement",
    DISPLAY_NAME: "Subcontract Agreement",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Suppliers Invoices",
    DISPLAY_NAME: "Suppliers Invoices",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: null,
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Valuation",
    DISPLAY_NAME: "Valuation",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
  {
    CATEGORY_NAME: "Variations",
    DISPLAY_NAME: "Variations",
    MODULE_NAME: "Project",
    IS_DEFAULT_COLUMN: "T",
    ATTACHMENT_LIMIT_IN_KB: null,
    PATH_FOR_LAN: null,
    PATH_FOR_REMOTE: null,
    IS_FILE_STORAGE: null,
  },
];

export default staticCategoryData;
